# Generated by Django 2.1.4 on 2019-01-31 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu', models.IntegerField()),
                ('seen', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('subj', models.CharField(max_length=500)),
                ('htmlt1', models.TextField()),
                ('htmlt2', models.TextField()),
                ('fmail', models.CharField(default=' ', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='dapis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='mservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lo', models.CharField(default='ukr_net', max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='otpr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na', models.CharField(max_length=100)),
                ('mservice', models.ManyToManyField(to='man.mservice')),
            ],
        ),
        migrations.AddField(
            model_name='dapis',
            name='otpr',
            field=models.ManyToManyField(through='man.bar', to='man.otpr'),
        ),
        migrations.AddField(
            model_name='bar',
            name='dapis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='man.dapis'),
        ),
        migrations.AddField(
            model_name='bar',
            name='otpr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='man.otpr'),
        ),
    ]
